apiVersion: v1
kind: Pod
metadata:
  name: web-server-1
spec:
  nodeName: gke-nfs-lock-cluster-default-pool-095e8a17-b7n8
  containers:
   - name: web-server
     image: nginx
     volumeMounts:
       - mountPath: /usr/share/nginx/html
         name: mypvc
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: preprov-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: preprov-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: my-pre-pv
  resources:
    requests:
      storage: 1Ti
