name: Cut Release
on:
  pull_request:
    types:
      - closed
    branches:
      - 'release-1.3'

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Get Latest Patch Version
      id: get_patch_version
      run: |
        LATEST_TAG=$(git tag | grep -E 'v1\.3\.[0-9]+' | grep -v 'rc' | sort -V | tail -n 1)
        PATCH_VERSION="${LATEST_TAG##*.}"
        NEW_TAG="v1.3.${PATCH_VERSION+1}"
        echo "::set-output name=patch_version::$NEW_TAG"
      shell: bash

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: ${{ steps.get_patch_version.outputs.patch_version }}

        
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: ${{ steps.get_patch_version.outputs.patch_version }}
